#!/bin/bash

TARGETDIR=$1
if [ -z "$TARGETDIR" ]; then
	TARGETDIR="."
fi
# search for sourcecode-files
SRCFILES=`find .. -type d -name testsuite -prune , \
                           -type f -name "*.h" \
                                -o -name "*.c"   \
                                -o -name "*.cc"  \
                                -o -name "*.cpp"`
echo $SRCFILES
echo "create $TARGETDIR/krb5-ticket-watcher.pot"
#calling xgettext with the sourcefiles
xgettext --debug -s --no-wrap --add-comments --add-location --keyword=ki18n --qt --foreign-user --copyright-holder="Michael Calmer, Nuernberg" --default-domain=krb5-ticket-watcher --output=$TARGETDIR/krb5-ticket-watcher.pot $SRCFILES

POFILES=`find $TARGETDIR -name "*.po"`
echo "$POFILES"
for P in $POFILES; do
	/usr/bin/msgmerge --update $P $TARGETDIR/krb5-ticket-watcher.pot
done
