name: build and cpack
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      #
      # matrix for containers
      #
      matrix:
        container:
          - ubuntu:22.04
          - ubuntu:20.04
          - debian:bullseye
          - debian:buster
          - centos:centos8
          - centos:latest
          - fedora:latest

    container:
      image: ${{ matrix.container }}

    #matrix:
    #  os: [ ubuntu-22.04, ubuntu-20.04 ]
    #  compiler: [ clang, gcc ]

    steps:
      - uses: actions/checkout@v3
      # install dependencies
      - name: devel-pkgs-ubuntu
        if: startsWith(matrix.container,'ubuntu') || startsWith(matrix.container,'debian')
        run: apt-get update -y && apt-get install -yq gettext krb5-user krb5-config libkrb5-dev make cmake qt5-default
      - name: devel-pkgs-centos
        if: startsWith(matrix.container,'centos') || startsWith(matrix.container,'fedora')
        run: yum update -y && yum install -yq gettext krb5-devel qt5-devel qt5-qtbase-devel qt5-qttools rpm-build
      # build project
      - name: mkdir
        run: mkdir cmake-build-release
      - name: cmake cmake-build-release
        run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -Bcmake-build-release -H.
      - name: cmake make
        run: cmake --build cmake-build-release/ --target all
        env:
          MAKEFLAGS: "-j2"
      - name: cpack-deb
        if: startsWith(matrix.container,'ubuntu') || startsWith(matrix.container,'debian')
        run: cd cmake-build-release && cpack -G DEB && cd ..
      - name: cpack-rpm
        if: startsWith(matrix.container,'centos') || startsWith(matrix.container,'fedora')
        run: cd cmake-build-release && cpack -G RPM && cd ..
      # upload artifact
      - name: Upload krb5-ticket-watcher binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('krb5-ticket-watcher-1.0.4.{0}', matrix.container) }}
          path: cmake-build-release/krb5-ticket-watcher-1.0.4-x86_64.???