name: build and cpack
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      #
      # matrix for containers
      #
      matrix:
        container:
          - ubuntu:22.04
          - ubuntu:20.04
    #          - debian:bullseye
    #          - debian:buster
    #          - centos:centos8
    #          - centos:latest
    #          - fedora:latest

    container:
      image: ${{ matrix.container }}

    #matrix:
    #  os: [ ubuntu-22.04, ubuntu-20.04 ]
    #  compiler: [ clang, gcc ]

    steps:
      - uses: actions/checkout@v3
      # install dependencies
      - name: devel-pkgs-ubuntu-20.04
        if: startsWith(matrix.container,'ubuntu:20.04') || startsWith(matrix.container,'debian')
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && 
          echo -e "krb5-config krb5-config/kerberos_servers string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/default_realm string TEST.HOME" | debconf-set-selections && 
          echo -e "heimdal-kdc heimdal/realm string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/admin_server string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/dns_for_default boolean true" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/add_servers boolean true" | debconf-set-selections && 
          apt-get update -y && apt-get install -yq gettext krb5-user krb5-config libkrb5-dev make cmake qt5-default gcc g++
      - name: devel-pkgs-ubuntu-latest
        if: startsWith(matrix.container,'ubuntu:22.04') || startsWith(matrix.container,'debian')
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && 
          echo -e "krb5-config krb5-config/kerberos_servers string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/default_realm string TEST.HOME" | debconf-set-selections && 
          echo -e "heimdal-kdc heimdal/realm string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/admin_server string TEST.HOME" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/dns_for_default boolean true" | debconf-set-selections && 
          echo -e "krb5-config krb5-config/add_servers boolean true" | debconf-set-selections && 
          apt-get update -y && apt-get install -yq gettext krb5-user krb5-config libkrb5-dev make cmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools gcc g++
      #      - name: devel-pkgs-centos
      #        if: startsWith(matrix.container,'centos') || startsWith(matrix.container,'fedora')
      #        run: yum update -y && yum install -yq gettext krb5-devel qt5-devel qt5-qtbase-devel qt5-qttools rpm-build
      # build project
      - name: mkdir
        run: mkdir cmake-build-release
      - name: cmake cmake-build-release
        run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -Bcmake-build-release -H.
      - name: cmake make
        run: cmake --build cmake-build-release/ --target all
        env:
          MAKEFLAGS: "-j2"
      - name: cpack-deb
        if: startsWith(matrix.container,'ubuntu') || startsWith(matrix.container,'debian')
        run: cd cmake-build-release && cpack -G DEB && cd ..
        #      - name: cpack-rpm
        #        if: startsWith(matrix.container,'centos') || startsWith(matrix.container,'fedora')
        #        run: cd cmake-build-release && cpack -G RPM && cd ..
        # upload artifact
      - uses: mad9000/actions-find-and-replace-string@2
        id: container
        with:
          source: ${{ matrix.container }}
          find: ':'        # we want to remove : from container name
          replace: '-'     # and replace it with -

      - name: Upload krb5-ticket-watcher binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('krb5-ticket-watcher-1.0.4.{0}', steps.container.outputs.value) }}
          path: cmake-build-release/krb5-ticket-watcher-1.0.4-x86_64.???